"use client";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { apiFetch, withQuery } from "@/lib/api/client";
import { formatWib } from "@/lib/formatters";
import { PageHeader } from "@/components/ui/page-header";
import { MetricCard, MetricGrid } from "@/components/ui/metric-card";
import { DataTable } from "@/components/ui/data-table";
import { CsvExport } from "@/components/ui/csv-export";
import { StatusBadge } from "@/components/ui/status-badge";
import { LoadingState, ErrorState } from "@/components/ui/page-state";
import { PlotlyChart } from "@/components/charts/plotly-chart";
import { toNumericTrendSeries } from "./transforms";
type Metric={device_name:string;metric_name:string;metric_value:string;metric_value_numeric:number|null;status:string|null;checked_at:string;unit:string|null};type Context={metric_names:string[];latest_snapshot:{items:Metric[];meta:{total:number}};history:{items:Metric[];meta:{total:number}};latest_snapshot_status_summary:Record<string,number>};
export function LiveMonitoringPage(){const[metric,setMetric]=useState("");const[status,setStatus]=useState("");const q=useQuery({queryKey:["live",metric,status],queryFn:()=>apiFetch<Context>(withQuery("/metrics/history/live",{metric_name:metric,status,snapshot_limit:50,limit:100})),refetchInterval:15000});if(q.isPending)return <LoadingState/>;if(q.isError)return <ErrorState message="Live monitoring tidak dapat dimuat." onRetry={()=>void q.refetch()}/>;const d=q.data;const anomalies=d.latest_snapshot.items.filter(x=>["warning","down","error"].includes(String(x.status))).length;const cols=[{key:"device",label:"Device",render:(x:Metric)=>x.device_name},{key:"metric",label:"Metrik",render:(x:Metric)=>x.metric_name},{key:"value",label:"Nilai",render:(x:Metric)=>`${x.metric_value}${x.unit?` ${x.unit}`:""}`},{key:"status",label:"Status",render:(x:Metric)=><StatusBadge value={x.status}/>},{key:"time",label:"Dicek (WIB)",render:(x:Metric)=>formatWib(x.checked_at)}];return <main className="app-page"><PageHeader title="Live Monitoring" description="Snapshot terbaru dan riwayat metric real-time."/><MetricGrid>{[["Total Data",d.history.meta.total],["Metrik Aktif",d.metric_names.length],["Snapshot",d.latest_snapshot.meta.total],["Anomali Aktif",anomalies]].map(([l,v])=><MetricCard key={String(l)} label={String(l)} value={String(v)}/>)}</MetricGrid><div className="filter-panel"><label>Metrik<select value={metric} onChange={e=>setMetric(e.target.value)}><option value="">Semua metric</option>{d.metric_names.map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Semua status</option>{["ok","warning","down","error"].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="section-header"><h2>Snapshot Terbaru</h2><CsvExport filename="live-snapshot.csv" columns={["Device","Metric","Value","Status","Checked WIB"]} rows={d.latest_snapshot.items.map(x=>[x.device_name,x.metric_name,x.metric_value,x.status,formatWib(x.checked_at)])}/></div><DataTable columns={cols} rows={d.latest_snapshot.items}/><div className="section-header"><h2>Riwayat Detail</h2><CsvExport filename="live-history.csv" columns={["Device","Metric","Value","Numeric","Status","Checked WIB"]} rows={d.history.items.map(x=>[x.device_name,x.metric_name,x.metric_value,x.metric_value_numeric,x.status,formatWib(x.checked_at)])}/></div><DataTable columns={cols} rows={d.history.items}/></main>}
