FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements ./requirements
RUN pip install --no-cache-dir -r requirements/dashboard.txt

COPY dashboard ./dashboard

EXPOSE 8501

CMD ["streamlit", "run", "dashboard/Overview.py", "--server.address=0.0.0.0", "--server.port=8501"]
