"use client";

import { useQuery } from "@tanstack/react-query";
import { type ReactNode, useState } from "react";
import { apiFetch } from "@/lib/api/client";
import { formatWib, statusLabel } from "@/lib/formatters";
import { ErrorState, LoadingState } from "@/components/ui/page-state";
import { MetaStrip } from "@/components/ui/meta-strip";
import { StatusBadge } from "@/components/ui/status-badge";
import { DataTable } from "@/components/ui/data-table";
import { CsvExport } from "@/components/ui/csv-export";
import { PermissionGate } from "@/components/ui/permission-gate";
import { FreshnessLabel } from "@/components/ui/freshness-label";
import { PlotlyChart, statusChartColor } from "@/components/charts/plotly-chart";
import type { OverviewData } from "./types";

type Tone = "neutral" | "success" | "warning" | "danger";
function tone(status: string): Tone { return ["up", "ok", "active"].includes(status.toLowerCase()) ? "success" : status.toLowerCase() === "warning" ? "warning" : ["down", "error", "critical", "high"].includes(status.toLowerCase()) ? "danger" : "neutral"; }
function Metric({ label, value, detail, tone: metricTone = "neutral" }: { label: string; value: string | number; detail: string; tone?: Tone }) { return <article className={`overview-metric overview-metric-${metricTone}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>; }

export function OverviewPage() {
  const overview = useQuery({ queryKey: ["overview"], queryFn: () => apiFetch<OverviewData>("/dashboard/overview-data"), refetchInterval: 15_000 });
  if (overview.isPending) return <LoadingState />;
  if (overview.isError) return <ErrorState message="Overview tidak dapat dimuat." onRetry={() => void overview.refetch()} />;
  const data = overview.data; const statuses = data.device_counts.statuses ?? {}; const problemRows = data.problem_devices.filter((item) => ["down", "warning", "error"].includes(item.latest_status));
  const services = [{ label: "Internet", value: data.summary.internet_status }, { label: "MikroTik", value: data.summary.mikrotik_status }, { label: "Server", value: data.summary.server_status }];
  return <main className="app-page overview-page">
    <section className="overview-hero" aria-labelledby="overview-title"><div className="overview-hero-copy"><p className="overview-eyebrow">Network operations center</p><h1 id="overview-title">Overview</h1><p>Ringkasan kesehatan jaringan, perangkat yang perlu perhatian, dan antrian respons aktif.</p><div className="overview-service-statuses">{services.map((item) => <div className="overview-service-status" key={item.label}><span>{item.label}</span><StatusBadge value={item.value} /></div>)}</div></div><div className="overview-hero-actions"><span>Auto-refresh setiap 15 detik</span><PermissionGate fallback={<span className="overview-read-only">Mode baca saja</span>}><RunCycleButton /></PermissionGate></div></section>
    <MetaStrip items={[{ label: "Refresh", value: "Aktif · 15 dtk" }, { label: "Diperbarui", value: formatWib(new Date().toISOString()) }, { label: "Check terakhir", value: formatWib(data.device_counts.latest_check_at) }]} />
    <section className="overview-section"><div className="overview-section-heading"><div><p className="overview-eyebrow">Health at a glance</p><h2>Status Global</h2></div><span>3 layanan inti dipantau</span></div><div className="overview-metric-grid">{services.map((item) => <Metric key={item.label} label={item.label} value={statusLabel(item.value)} tone={tone(item.value)} detail="Status layanan saat ini" />)}<Metric label="Alert Aktif" value={data.summary.active_alerts} tone={data.summary.active_alerts ? "danger" : "success"} detail={data.summary.active_alerts ? "Butuh perhatian operator" : "Tidak ada alert aktif"} /></div></section>
    <section className="overview-section"><div className="overview-section-heading"><div><p className="overview-eyebrow">Operational snapshot</p><h2>Kondisi Perangkat</h2></div><span>{data.device_counts.total} device terdaftar</span></div><div className="overview-metric-grid overview-metric-grid-five"><Metric label="Total Device" value={data.device_counts.total} detail="Seluruh inventory" /><Metric label="Device Aktif" value={data.device_counts.active} tone="success" detail="Siap dimonitor" /><Metric label="Device Down" value={statuses.down ?? 0} tone={(statuses.down ?? 0) ? "danger" : "success"} detail="Perlu investigasi" /><Metric label="Device Warning" value={statuses.warning ?? 0} tone={(statuses.warning ?? 0) ? "warning" : "success"} detail="Di luar kondisi ideal" /><Metric label="Insiden Aktif" value={data.incidents.length} tone={data.incidents.length ? "warning" : "success"} detail="Tercatat pada antrian" /></div></section>
    <section className="overview-panel-grid"><article className="overview-panel"><PanelHeader eyebrow="Needs attention" title="Device Perlu Perhatian" description="Perangkat dengan kondisi down, warning, atau error." action={<CsvExport filename="device-perlu-perhatian.csv" columns={["Device", "IP", "Tipe", "Site", "Status", "Freshness", "Dicek WIB"]} rows={problemRows.map((item) => [item.name, item.ip_address, item.device_type, item.site, item.latest_status, item.latest_checked_at, formatWib(item.latest_checked_at)])} />} /><DataTable columns={[{ key: "name", label: "Device", render: (item) => item.name }, { key: "ip", label: "IP Address", render: (item) => item.ip_address }, { key: "type", label: "Type", render: (item) => item.device_type }, { key: "site", label: "Site", render: (item) => item.site ?? "-" }, { key: "status", label: "Status", render: (item) => <StatusBadge value={item.latest_status} /> }, { key: "freshness", label: "Freshness", render: (item) => <FreshnessLabel checkedAt={item.latest_checked_at} /> }, { key: "checked", label: "Pemeriksaan Terakhir (WIB)", render: (item) => formatWib(item.latest_checked_at) }]} rows={problemRows} /></article><article className="overview-panel"><PanelHeader eyebrow="Alert mix" title="Distribusi Alert" description="Prioritas berdasarkan tingkat severity aktif." /><PlotlyChart ariaLabel="Distribusi tingkat alert aktif" data={[{ type: "bar", orientation: "h", x: Object.values(data.alert_severity_summary), y: Object.keys(data.alert_severity_summary), marker: { color: Object.keys(data.alert_severity_summary).map(statusChartColor) }, hovertemplate: "%{y}: %{x}<extra></extra>" }]} layout={{ xaxis: { title: { text: "Jumlah alert" } }, yaxis: { automargin: true, autorange: "reversed" } }} /><DataTable columns={[{ key: "severity", label: "Tingkat", render: ([severity]) => <StatusBadge value={severity} /> }, { key: "count", label: "Jumlah", render: ([, count]) => count }]} rows={Object.entries(data.alert_severity_summary)} /></article></section>
    <section className="overview-panel-grid"><article className="overview-panel"><PanelHeader eyebrow="Response queue" title="Alert Aktif Terbaru" /><DataTable columns={[{ key: "created", label: "Dibuat (WIB)", render: (item) => formatWib(item.created_at) }, { key: "device", label: "Device", render: (item) => item.device_name }, { key: "severity", label: "Tingkat", render: (item) => <StatusBadge value={item.severity} /> }, { key: "message", label: "Pesan", render: (item) => item.message }]} rows={data.alerts.slice(0, 8)} pageSize={null} /></article><article className="overview-panel"><PanelHeader eyebrow="Incident queue" title="Insiden Aktif" /><DataTable columns={[{ key: "started", label: "Mulai (WIB)", render: (item) => formatWib(item.started_at) }, { key: "device", label: "Device", render: (item) => item.device_name }, { key: "summary", label: "Ringkasan", render: (item) => item.summary }, { key: "status", label: "Status", render: (item) => <StatusBadge value={item.status} /> }]} rows={data.incidents.slice(0, 8)} pageSize={null} /></article></section>
    <section className="overview-panel"><PanelHeader eyebrow="Telemetry feed" title="Snapshot Metric Terbaru" description="Metric paling baru dari device yang dipantau." action={<CsvExport filename="snapshot-metric-terbaru.csv" columns={["Dicek WIB", "Device", "Metrik", "Nilai", "Status", "Freshness"]} rows={data.latest_snapshot.items.map((item) => [formatWib(item.checked_at), item.device_name, item.metric_name, `${item.metric_value}${item.unit ? ` ${item.unit}` : ""}`, item.status, item.checked_at])} />} /><DataTable columns={[{ key: "checked", label: "Dicek (WIB)", render: (item) => formatWib(item.checked_at) }, { key: "device", label: "Device", render: (item) => item.device_name }, { key: "metric", label: "Metrik", render: (item) => item.metric_name }, { key: "value", label: "Nilai", render: (item) => `${item.metric_value}${item.unit ? ` ${item.unit}` : ""}` }, { key: "status", label: "Status", render: (item) => <StatusBadge value={item.status} /> }, { key: "freshness", label: "Freshness", render: (item) => <FreshnessLabel checkedAt={item.checked_at} /> }]} rows={data.latest_snapshot.items.slice(0, 12)} pageSize={null} /></section>
  </main>;
}

function PanelHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description?: string; action?: ReactNode }) { return <div className="overview-panel-header"><div><p className="overview-eyebrow">{eyebrow}</p><h2>{title}</h2>{description ? <p>{description}</p> : null}</div>{action}</div>; }
function RunCycleButton() { const [pending, setPending] = useState(false); async function run() { setPending(true); try { await apiFetch("/system/run-cycle", { method: "POST" }); } finally { setPending(false); } } return <button type="button" className="overview-run-cycle" disabled={pending} onClick={() => void run()}>{pending ? "Menjalankan…" : "Jalankan Monitoring Cycle"}</button>; }
