"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { StatusBadge } from "@/components/status-badge";
import { ApiError, apiRequest } from "@/lib/api";
import { useAuth } from "@/lib/auth";
import { downloadCsv, formatWib } from "@/lib/presentation";

const PAGE_SIZE = 25;
type Alert = { id: number; device_id?: number | null; device_name?: string | null; site?: string | null; alert_type: string; severity: string; message: string; status: string; created_at: string };
type Page = { items: Alert[]; meta: { total: number; limit: number; offset: number } };
type DeviceOption = { id: number; name: string; device_type: string; site?: string | null };
const age = (createdAt: string) => { const mins = Math.max(0, Math.floor((Date.now() - new Date(createdAt).getTime()) / 60_000)); return mins < 60 ? `${mins} menit` : mins < 1440 ? `${Math.floor(mins / 60)} jam` : `${Math.floor(mins / 1440)} hari`; };

export function AlertsDashboard() {
  const { ready, user, token } = useAuth(); const router = useRouter(); const pathname = usePathname(); const params = useSearchParams();
  const [page, setPage] = useState<Page | null>(null); const [devices, setDevices] = useState<DeviceOption[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<ApiError | null>(null);
  const severity = params.get("severity") || ""; const site = params.get("site") || ""; const alertType = params.get("alert_type") || ""; const deviceId = params.get("device_id") || ""; const search = params.get("search") || ""; const offset = Math.max(0, Number(params.get("offset") || 0));
  const update = (changes: Record<string, string | null>) => { const next = new URLSearchParams(params.toString()); Object.entries(changes).forEach(([key, value]) => value ? next.set(key, value) : next.delete(key)); router.replace(`${pathname}?${next}`); };
  const load = useCallback(async () => { if (!token) return; setError(null); try { const query = new URLSearchParams({ limit: String(PAGE_SIZE), offset: String(offset) }); if (severity) query.set("severity", severity); if (site) query.set("site", site); if (alertType) query.set("alert_type", alertType); if (deviceId) query.set("device_id", deviceId); if (search) query.set("search", search); const [alerts, options] = await Promise.all([apiRequest<Page>(`/alerts/active/paged?${query}`, { cache: "no-store" }, token), apiRequest<DeviceOption[]>("/devices/options?active_only=true&limit=1000", { cache: "no-store" }, token)]); setPage(alerts); setDevices(options); } catch (caught) { setError(caught instanceof ApiError ? caught : new ApiError(0, "Koneksi ke backend gagal.")); } finally { setLoading(false); } }, [token, offset, severity, site, alertType, deviceId, search]);
  useEffect(() => { if (ready && token) void load(); }, [ready, token, load]);
  if (!ready || !user) return <div className="login">Memulihkan sesi…</div>;
  const rows = page?.items || [], total = page?.meta.total || 0; const types = [...new Set(rows.map((row) => row.alert_type))].sort();
  return <AppShell><header className="page-header"><div><h1 className="page-title">Alerts</h1><p className="page-description">Alert aktif untuk triage. Monitoring degraded dibedakan dari alert kondisi device.</p></div><button className="button button-secondary button-inline" onClick={() => void load()} disabled={loading}>{loading ? "Memuat…" : "Refresh"}</button></header>
    <section className="panel filters"><label className="field"><span>Severity</span><select value={severity} onChange={(event) => update({ severity: event.target.value || null, offset: "0" })}><option value="">Semua severity</option><option value="critical">Critical</option><option value="warning">Warning</option><option value="info">Info</option></select></label><label className="field"><span>Device</span><select value={deviceId} onChange={(event) => update({ device_id: event.target.value || null, offset: "0" })}><option value="">Semua device</option>{devices.map((device) => <option key={device.id} value={device.id}>{device.name}</option>)}</select></label><label className="field"><span>Tipe alert</span><select value={alertType} onChange={(event) => update({ alert_type: event.target.value || null, offset: "0" })}><option value="">Semua tipe</option>{types.map((value) => <option key={value}>{value}</option>)}</select></label><label className="field"><span>Site</span><input placeholder="Contoh: Jakarta" value={site} onChange={(event) => update({ site: event.target.value || null, offset: "0" })} /></label><label className="field"><span>Cari device/pesan</span><input placeholder="Nama device atau kata kunci" value={search} onChange={(event) => update({ search: event.target.value || null, offset: "0" })} /></label><button className="button button-secondary button-inline filter-reset" onClick={() => update({ severity: null, site: null, alert_type: null, device_id: null, search: null, offset: "0" })}>Reset filter</button></section>
    {error && <div className="alert-box error-box"><span>{error.message}</span><button className="button button-secondary button-inline" onClick={() => void load()}>Coba lagi</button>{error.requestId && <small>Request ID: {error.requestId}</small>}</div>}
    {loading && !page ? <section className="panel">Memuat alert aktif…</section> : <section className="panel table-panel"><div className="section-heading"><h2>{total} alert aktif</h2><button className="button button-secondary button-inline" onClick={() => downloadCsv("active_alerts.csv", ["Dibuat (WIB)", "Age", "Severity", "Device", "Site", "Tipe", "Status", "Pesan"], rows.map((row) => [formatWib(row.created_at), age(row.created_at), row.severity, row.device_name || "-", row.site || "-", row.alert_type, row.status, row.message]))}>Download CSV</button></div>{rows.length ? <><div className="table-scroll"><table><thead><tr><th>Dibuat</th><th>Age</th><th>Severity</th><th>Device</th><th>Site</th><th>Tipe</th><th>Status</th><th>Pesan</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{formatWib(row.created_at)}</td><td>{age(row.created_at)}</td><td><StatusBadge value={row.severity} /></td><td>{row.device_id ? <Link href={`/live-monitoring?device_id=${row.device_id}`}>{row.device_name || `Device ${row.device_id}`}</Link> : row.device_name || "-"}</td><td>{row.site || "-"}</td><td>{row.alert_type.replaceAll("_", " ")}</td><td><StatusBadge value={row.status} /></td><td>{row.message}</td></tr>)}</tbody></table></div><div className="pagination"><span>{offset + 1}–{Math.min(offset + PAGE_SIZE, total)} dari {total}</span><button className="button button-secondary button-inline" disabled={offset === 0} onClick={() => update({ offset: String(Math.max(0, offset - PAGE_SIZE)) })}>Sebelumnya</button><button className="button button-secondary button-inline" disabled={offset + PAGE_SIZE >= total} onClick={() => update({ offset: String(offset + PAGE_SIZE) })}>Berikutnya</button></div></> : <p className="empty-state">Tidak ada alert aktif untuk filter ini.</p>}</section>}</AppShell>;
}
