"use client";

import dynamic from "next/dynamic";
import { useCallback, useEffect, useMemo, useState } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { AppShell } from "@/components/app-shell";
import { ApiError, apiRequest } from "@/lib/api";
import { useAuth } from "@/lib/auth";
import { downloadCsv, formatNumber, formatWib } from "@/lib/presentation";

const Plot = dynamic(() => import("react-plotly.js"), { ssr: false });
const PAGE_SIZE = 25;
type Item = { id: number; device_id: number; device_name: string; device_type?: string | null; rollup_date: string; total_samples: number; ping_samples: number; down_count: number; uptime_percentage?: number | null; average_ping_ms?: number | null; average_packet_loss_percent?: number | null; average_jitter_ms?: number | null; max_jitter_ms?: number | null; updated_at: string };
type Page = { items: Item[]; meta: { total: number; limit: number; offset: number } };
type Device = { id: number; name: string; device_type: string; site?: string | null };

const dateValue = (value: string | null) => value || "";
const asDate = (date: Date) => date.toISOString().slice(0, 10);
function todayMinus(days: number) { const value = new Date(); value.setDate(value.getDate() - days); return asDate(value); }

export function DailySummaryDashboard() {
  const { ready, user, token } = useAuth(); const router = useRouter(); const pathname = usePathname(); const params = useSearchParams();
  const [page, setPage] = useState<Page | null>(null); const [devices, setDevices] = useState<Device[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<ApiError | null>(null);
  const deviceId = params.get("device_id") || ""; const from = dateValue(params.get("from")) || todayMinus(6); const to = dateValue(params.get("to")) || asDate(new Date()); const offset = Math.max(0, Number(params.get("offset") || 0));
  const update = (changes: Record<string, string | null>) => { const next = new URLSearchParams(params.toString()); Object.entries(changes).forEach(([key, value]) => value ? next.set(key, value) : next.delete(key)); router.replace(`${pathname}?${next.toString()}`); };
  const load = useCallback(async () => { if (!token) return; setError(null); try { const query = new URLSearchParams({ limit: String(PAGE_SIZE), offset: String(offset), rollup_from: from, rollup_to: to }); if (deviceId) query.set("device_id", deviceId); const [summary, options] = await Promise.all([apiRequest<Page>(`/metrics/daily-summary?${query}`, { cache: "no-store" }, token), apiRequest<Device[]>("/devices/options?active_only=true&limit=1000", { cache: "no-store" }, token)]); setPage(summary); setDevices(options); } catch (caught) { setError(caught instanceof ApiError ? caught : new ApiError(0, "Koneksi ke backend gagal.")); } finally { setLoading(false); } }, [token, offset, from, to, deviceId]);
  useEffect(() => { if (ready && token) void load(); }, [ready, token, load]);
  const chart = useMemo(() => ({ x: (page?.items || []).map((row) => row.rollup_date), uptime: (page?.items || []).map((row) => row.uptime_percentage), ping: (page?.items || []).map((row) => row.average_ping_ms) }), [page]);
  if (!ready || !user) return <div className="login">Memulihkan sesi…</div>;
  const rows = page?.items || [], total = page?.meta.total || 0;
  return <AppShell><header className="page-header"><div><h1 className="page-title">Daily Summary</h1><p className="page-description">Rekap rollup harian availability dan kualitas koneksi; tidak memuat raw metric tanpa batas.</p></div><button className="button button-secondary button-inline" onClick={() => void load()} disabled={loading}>{loading ? "Memuat…" : "Refresh"}</button></header>
    <section className="panel filters"><label className="field"><span>Dari tanggal</span><input type="date" value={from} max={to} onChange={(event) => update({ from: event.target.value, offset: "0" })} /></label><label className="field"><span>Sampai tanggal</span><input type="date" value={to} min={from} onChange={(event) => update({ to: event.target.value, offset: "0" })} /></label><label className="field"><span>Device</span><select value={deviceId} onChange={(event) => update({ device_id: event.target.value || null, offset: "0" })}><option value="">Semua device</option>{devices.map((device) => <option key={device.id} value={device.id}>{device.name} · {device.device_type}{device.site ? ` · ${device.site}` : ""}</option>)}</select></label><button className="button button-secondary button-inline filter-reset" onClick={() => update({ from: todayMinus(6), to: asDate(new Date()), device_id: null, offset: "0" })}>Reset filter</button></section>
    {error && <div className="alert-box error-box"><span>{error.message}</span><button className="button button-secondary button-inline" onClick={() => void load()}>Coba lagi</button>{error.requestId && <small>Request ID: {error.requestId}</small>}</div>}
    {loading && !page ? <section className="panel">Memuat ringkasan harian…</section> : <><section className="kpi-grid four"><Kpi label="Baris rollup" value={formatNumber(total)} /><Kpi label="Availability rata-rata" value={formatNumber(average(rows.map((row) => row.uptime_percentage)), "%")} /><Kpi label="Ping rata-rata" value={formatNumber(average(rows.map((row) => row.average_ping_ms)), " ms")} /><Kpi label="Packet loss rata-rata" value={formatNumber(average(rows.map((row) => row.average_packet_loss_percent)), "%")} /></section>
      <section className="panel chart-panel"><div className="section-heading"><h2>Tren pada halaman saat ini</h2><span className="muted">Availability dan ping per device/tanggal</span></div>{rows.length ? <Plot data={[{ type: "scatter", mode: "lines+markers", name: "Availability (%)", x: chart.x, y: chart.uptime }, { type: "scatter", mode: "lines+markers", name: "Ping rata-rata (ms)", x: chart.x, y: chart.ping, yaxis: "y2" }]} layout={{ autosize: true, height: 340, paper_bgcolor: "transparent", plot_bgcolor: "transparent", font: { color: "#f5f7fb" }, margin: { l: 52, r: 52, t: 15, b: 55 }, xaxis: { title: { text: "Tanggal" }, gridcolor: "#2d3746" }, yaxis: { title: { text: "Availability (%)" }, rangemode: "tozero", gridcolor: "#2d3746" }, yaxis2: { title: { text: "Ping (ms)" }, overlaying: "y" as never, side: "right" }, legend: { orientation: "h" } }} config={{ displayModeBar: false, responsive: true }} style={{ width: "100%" }} /> : <p className="empty-state">Tidak ada rollup pada rentang filter ini.</p>}</section>
      <section className="panel table-panel"><div className="section-heading"><h2>Daily Rollup</h2><button className="button button-secondary button-inline" onClick={() => downloadCsv("daily_summary.csv", ["Tanggal", "Device", "Tipe", "Sampel", "Down", "Availability (%)", "Ping rata-rata (ms)", "Packet loss (%)", "Jitter rata-rata (ms)", "Diubah (WIB)"], rows.map((row) => [row.rollup_date, row.device_name, row.device_type || "-", row.total_samples, row.down_count, formatNumber(row.uptime_percentage), formatNumber(row.average_ping_ms), formatNumber(row.average_packet_loss_percent), formatNumber(row.average_jitter_ms), formatWib(row.updated_at)]))}>Download CSV</button></div>{rows.length ? <><div className="table-scroll"><table><thead><tr><th>Tanggal</th><th>Device</th><th>Tipe</th><th>Sampel</th><th>Down</th><th>Availability</th><th>Ping</th><th>Packet loss</th><th>Jitter</th><th>Diubah</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.rollup_date}</td><td>{row.device_name}</td><td>{row.device_type || "-"}</td><td>{row.total_samples}</td><td>{row.down_count}</td><td>{formatNumber(row.uptime_percentage, "%")}</td><td>{formatNumber(row.average_ping_ms, " ms")}</td><td>{formatNumber(row.average_packet_loss_percent, "%")}</td><td>{formatNumber(row.average_jitter_ms, " ms")}</td><td>{formatWib(row.updated_at)}</td></tr>)}</tbody></table></div><div className="pagination"><span>{total ? `${offset + 1}–${Math.min(offset + PAGE_SIZE, total)} dari ${total}` : "0 data"}</span><button className="button button-secondary button-inline" disabled={offset === 0} onClick={() => update({ offset: String(Math.max(0, offset - PAGE_SIZE)) })}>Sebelumnya</button><button className="button button-secondary button-inline" disabled={offset + PAGE_SIZE >= total} onClick={() => update({ offset: String(offset + PAGE_SIZE) })}>Berikutnya</button></div></> : <p className="empty-state">Tidak ada data untuk filter ini.</p>}</section></>}</AppShell>;
}
function average(values: Array<number | null | undefined>) { const numeric = values.filter((value): value is number => typeof value === "number" && Number.isFinite(value)); return numeric.length ? numeric.reduce((sum, value) => sum + value, 0) / numeric.length : null; }
function Kpi({ label, value }: { label: string; value: React.ReactNode }) { return <article className="kpi-card"><span>{label}</span><strong>{value}</strong></article>; }
