"use client";

import { ChangeEvent, useState } from "react";
import { ApiError, apiRequest } from "@/lib/api";

type DeviceType = { value: string; label: string };
type Existing = { ip_address: string };
type ImportRow = { row: number; name: string; ip_address: string; device_type: string; site: string; location: string | null; description: string | null; is_active: boolean };
type ErrorRow = { row: number; error: string };

function parseCsv(text: string) {
  const rows: string[][] = []; let row: string[] = []; let value = ""; let quoted = false;
  for (let index = 0; index < text.length; index += 1) { const char = text[index]; if (char === '"') { if (quoted && text[index + 1] === '"') { value += '"'; index += 1; } else quoted = !quoted; } else if (char === "," && !quoted) { row.push(value.trim()); value = ""; } else if ((char === "\n" || char === "\r") && !quoted) { if (char === "\r" && text[index + 1] === "\n") index += 1; row.push(value.trim()); if (row.some(Boolean)) rows.push(row); row = []; value = ""; } else value += char; }
  row.push(value.trim()); if (row.some(Boolean)) rows.push(row); return rows;
}
function boolValue(value: string) { const normalized = value.trim().toLowerCase(); if (["", "1", "true", "yes", "y", "aktif", "active"].includes(normalized)) return true; if (["0", "false", "no", "n", "nonaktif", "inactive"].includes(normalized)) return false; throw new Error("is_active harus true/false atau kosong"); }
function validIp(value: string) { const parts = value.split("."); return parts.length === 4 && parts.every((part) => /^\d+$/.test(part) && Number(part) >= 0 && Number(part) <= 255); }

export function DeviceCsvImport({ types, token, onImported }: { types: DeviceType[]; token: string | null; onImported: () => Promise<void> }) {
  const [valid, setValid] = useState<ImportRow[]>([]); const [errors, setErrors] = useState<ErrorRow[]>([]); const [filename, setFilename] = useState(""); const [loading, setLoading] = useState(false); const [message, setMessage] = useState("");
  const dryRun = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; setValid([]); setErrors([]); setMessage(""); if (!file || !token) return; setFilename(file.name); setLoading(true); try { const [source, existing] = await Promise.all([file.text(), apiRequest<Existing[]>("/devices/options?limit=1000", { cache: "no-store" }, token)]); const rows = parseCsv(source); const header = rows.shift()?.map((value) => value.toLowerCase().trim()) || []; const required = ["name", "ip_address", "device_type", "site"]; const missing = required.filter((key) => !header.includes(key)); if (missing.length) { setErrors([{ row: 1, error: `Kolom wajib hilang: ${missing.join(", ")}` }]); return; } const index = (key: string) => header.indexOf(key); const existingIps = new Set(existing.map((item) => item.ip_address.trim())); const fileIps = new Set<string>(); const allowed = new Set(types.map((item) => item.value)); const result: ImportRow[] = []; const issues: ErrorRow[] = []; rows.forEach((sourceRow, rowIndex) => { const read = (key: string) => sourceRow[index(key)]?.trim() || ""; const ip_address = read("ip_address"); const rowErrors: string[] = []; if (!read("name")) rowErrors.push("name kosong"); if (!validIp(ip_address)) rowErrors.push("ip_address tidak valid"); if (fileIps.has(ip_address)) rowErrors.push("ip_address duplikat di file"); if (existingIps.has(ip_address)) rowErrors.push("ip_address sudah ada di inventory"); fileIps.add(ip_address); if (!allowed.has(read("device_type"))) rowErrors.push("device_type tidak didukung"); if (!read("site")) rowErrors.push("site wajib diisi"); let is_active = true; try { is_active = boolValue(read("is_active")); } catch (caught) { rowErrors.push(caught instanceof Error ? caught.message : "is_active tidak valid"); } if (rowErrors.length) issues.push({ row: rowIndex + 2, error: rowErrors.join("; ") }); else result.push({ row: rowIndex + 2, name: read("name"), ip_address, device_type: read("device_type"), site: read("site"), location: read("location") || null, description: read("description") || null, is_active }); }); setValid(result); setErrors(issues); } catch (caught) { setErrors([{ row: 0, error: caught instanceof ApiError ? caught.message : "CSV tidak bisa dibaca." }]); } finally { setLoading(false); } };
  const importRows = async () => { if (!token || !valid.length || errors.length) return; setLoading(true); setMessage(""); const failed: ErrorRow[] = []; let created = 0; for (const row of valid) { try { await apiRequest("/devices", { method: "POST", body: JSON.stringify({ ...row, row: undefined }) }, token); created += 1; } catch (caught) { failed.push({ row: row.row, error: caught instanceof ApiError ? caught.message : "Gagal membuat device" }); } } setErrors(failed); setMessage(failed.length ? `Import sebagian selesai: ${created} berhasil, ${failed.length} gagal.` : `Import selesai: ${created} device ditambahkan.`); if (!failed.length) setValid([]); await onImported(); setLoading(false); };
  return <section className="panel section-block"><h2 className="section-title">Import CSV Device</h2><p className="muted">Kolom wajib: <code>name, ip_address, device_type, site</code>. Opsional: <code>location, description, is_active</code>. Dry-run tidak menulis data.</p><label className="field"><span>File CSV</span><input type="file" accept=".csv,text/csv" onChange={(event) => void dryRun(event)} /></label>{loading && <p className="muted">Memproses {filename}…</p>}{errors.length > 0 && <div className="alert-box error-box"><div><strong>Dry-run gagal.</strong><div className="table-scroll"><table><thead><tr><th>Baris</th><th>Error</th></tr></thead><tbody>{errors.map((issue) => <tr key={`${issue.row}-${issue.error}`}><td>{issue.row || "-"}</td><td>{issue.error}</td></tr>)}</tbody></table></div></div></div>}{valid.length > 0 && errors.length === 0 && <><p className="notice">Dry-run valid: {valid.length} device siap di-import.</p><div className="table-scroll"><table><thead><tr><th>Baris</th><th>Nama</th><th>IP</th><th>Tipe</th><th>Site</th><th>Aktif</th></tr></thead><tbody>{valid.map((row) => <tr key={row.row}><td>{row.row}</td><td>{row.name}</td><td>{row.ip_address}</td><td>{row.device_type}</td><td>{row.site}</td><td>{row.is_active ? "Ya" : "Tidak"}</td></tr>)}</tbody></table></div><button className="button button-inline" disabled={loading} onClick={() => void importRows()}>Import {valid.length} device valid</button></>}{message && <p className="notice">{message}</p>}</section>;
}
