"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { ApiError, apiRequest } from "@/lib/api";
import { useAuth } from "@/lib/auth";
import { formatWib } from "@/lib/presentation";

type Me = { id: number; username: string; full_name: string; role: string; expires_at?: string | null };
type Session = { session_id: number; client_ip: string; user_agent: string; created_at: string; last_seen_at: string; expires_at: string; is_current: boolean };

export function ProfileDashboard() {
  const { ready, user, token, logout } = useAuth();
  const [me, setMe] = useState<Me | null>(null); const [sessions, setSessions] = useState<Session[]>([]); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { if (!token) return; setLoading(true); setError(""); try { const [identity, activeSessions] = await Promise.all([apiRequest<Me>("/auth/me", { cache: "no-store" }, token), apiRequest<Session[]>("/auth/sessions", { cache: "no-store" }, token)]); setMe(identity); setSessions(activeSessions); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Koneksi ke backend gagal."); } finally { setLoading(false); } }, [token]);
  useEffect(() => { if (ready && token) void load(); }, [ready, token, load]);
  if (!ready || !user) return <div className="login">Memulihkan sesi…</div>;
  const changePassword = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!token) return; const form = new FormData(event.currentTarget); const current_password = String(form.get("current_password") || ""); const new_password = String(form.get("new_password") || ""); const confirm = String(form.get("confirm") || ""); if (new_password !== confirm) { setError("Konfirmasi password baru tidak sama."); return; } setSaving(true); setError(""); setNotice(""); try { await apiRequest("/auth/change-password", { method: "POST", body: JSON.stringify({ current_password, new_password }) }, token); event.currentTarget.reset(); setNotice("Password berhasil diperbarui. Sesi lain telah dicabut oleh backend."); await load(); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Password gagal diperbarui."); } finally { setSaving(false); } };
  const logoutOthers = async () => { if (!token) return; setSaving(true); setError(""); try { const result = await apiRequest<{ revoked_sessions: number }>("/auth/logout-all", { method: "POST" }, token); setNotice(`${result.revoked_sessions} sesi lain dicabut.`); await load(); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Gagal mencabut sesi lain."); } finally { setSaving(false); } };
  return <AppShell><header className="page-header"><div><h1 className="page-title">Profil & Session</h1><p className="page-description">Kelola identitas, password, dan sesi aktif akun Anda.</p></div><button className="button button-secondary button-inline" onClick={() => void load()} disabled={loading}>Refresh</button></header>{error && <div className="alert-box error-box">{error}</div>}{notice && <div className="alert-box success-box">{notice}</div>}<section className="panel profile-grid"><div><span className="muted">Nama</span><h2>{me?.full_name || user.full_name}</h2><p className="meta-row">@{me?.username || user.username} · {me?.role || user.role}</p></div><dl><dt>Sesi berakhir</dt><dd>{formatWib(me?.expires_at)}</dd><dt>Sesi aktif</dt><dd>{sessions.length}</dd></dl></section><div className="overview-split equal"><section className="panel"><h2 className="section-title">Ubah password</h2><form onSubmit={changePassword}><label className="field"><span>Password saat ini</span><input name="current_password" type="password" required autoComplete="current-password" /></label><label className="field"><span>Password baru</span><input name="new_password" type="password" required minLength={1} autoComplete="new-password" /></label><label className="field"><span>Konfirmasi password baru</span><input name="confirm" type="password" required minLength={1} autoComplete="new-password" /></label><button className="button" disabled={saving}>{saving ? "Menyimpan…" : "Ubah password"}</button></form></section><section className="panel"><h2 className="section-title">Keamanan sesi</h2><p className="page-description">Cabut seluruh sesi lain. Sesi yang sedang dipakai tetap aktif.</p><button className="button button-secondary" disabled={saving || sessions.length < 2} onClick={() => void logoutOthers()}>Logout dari sesi lain</button><button className="text-button danger" onClick={() => void logout()}>Logout dari perangkat ini</button></section></div><section className="panel table-panel section-block"><div className="section-heading"><h2>Sesi aktif</h2></div>{loading ? <p className="empty-state">Memuat sesi…</p> : sessions.length ? <div className="table-scroll"><table><thead><tr><th>Status</th><th>IP</th><th>Perangkat</th><th>Dibuat</th><th>Terakhir aktif</th><th>Berakhir</th></tr></thead><tbody>{sessions.map((session) => <tr key={session.session_id}><td>{session.is_current ? "Sesi ini" : "Aktif"}</td><td>{session.client_ip || "-"}</td><td>{session.user_agent || "-"}</td><td>{formatWib(session.created_at)}</td><td>{formatWib(session.last_seen_at)}</td><td>{formatWib(session.expires_at)}</td></tr>)}</tbody></table></div> : <p className="empty-state">Tidak ada data sesi aktif.</p>}</section></AppShell>;
}
