"use client";

import { useCallback, useEffect, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { StatusBadge } from "@/components/status-badge";
import { ApiError, apiRequest } from "@/lib/api";
import { useAuth } from "@/lib/auth";
import { downloadCsv, formatAge, formatNumber, formatWib } from "@/lib/presentation";

const REFRESH_MS = 30_000;
type Row = Record<string, unknown>;
type Observability = { database: string; metrics_latest_snapshot: number; incidents_active: number; database_pool: Row; pipeline_locks: Row; scheduler_queue: { lagging_jobs: number; misfire_count: number; note: string }; raw_metric_write_rate: { last_hour: number; per_minute_last_hour: number }; scheduler_health: Row[]; collector_health: Row[]; collector_health_window_hours: number; collector_runs: Row[]; operational_alerts: Row[] };
type Freshness = { generated_at: string; stale_after_minutes: number; items: Row[] };
type Budget = { endpoint: string; max_p95_ms: number; max_payload_rows: number; notes: string };

const cell = (row: Row, key: string) => row[key] as string | number | null | undefined;
function Table({ title, headers, rows, csvRows, render }: { title: string; headers: string[]; rows: Row[]; csvRows: Array<Array<string | number | null | undefined>>; render: (row: Row) => React.ReactNode }) {
  return <section className="panel table-panel"><div className="section-heading"><h2>{title}</h2><button className="button button-secondary button-inline" onClick={() => downloadCsv(`${title.toLowerCase().replaceAll(" ", "_")}.csv`, headers, csvRows)}>Download CSV</button></div>{rows.length ? <div className="table-scroll"><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map(render)}</tbody></table></div> : <p className="empty-state">Belum ada data untuk ditampilkan.</p>}</section>;
}
function Kpi({ label, value }: { label: string; value: React.ReactNode }) { return <article className="kpi-card"><span>{label}</span><strong>{value}</strong></article>; }

export function SystemHealthDashboard() {
  const { ready, user, token } = useAuth();
  const [data, setData] = useState<Observability | null>(null); const [freshness, setFreshness] = useState<Freshness | null>(null); const [budgets, setBudgets] = useState<Budget[]>([]);
  const [autoRefresh, setAutoRefresh] = useState(true); const [loading, setLoading] = useState(true); const [error, setError] = useState<ApiError | null>(null); const [updatedAt, setUpdatedAt] = useState<Date | null>(null);
  const load = useCallback(async () => { if (!token) return; setError(null); try { const [summary, fresh, budget] = await Promise.all([apiRequest<Observability>("/observability/summary", { cache: "no-store" }, token), apiRequest<Freshness>("/metrics/freshness/summary", { cache: "no-store" }, token), apiRequest<{ items: Budget[] }>("/system/performance-budgets", { cache: "no-store" }, token)]); setData(summary); setFreshness(fresh); setBudgets(budget.items); setUpdatedAt(new Date()); } catch (caught) { setError(caught instanceof ApiError ? caught : new ApiError(0, "Koneksi ke backend gagal.")); } finally { setLoading(false); } }, [token]);
  useEffect(() => { if (ready && token) void load(); }, [ready, token, load]);
  useEffect(() => { if (!autoRefresh || !token) return; const refresh = () => { if (!document.hidden) void load(); }; const timer = window.setInterval(refresh, REFRESH_MS); document.addEventListener("visibilitychange", refresh); return () => { window.clearInterval(timer); document.removeEventListener("visibilitychange", refresh); }; }, [autoRefresh, token, load]);
  if (!ready || !user) return <div className="login">Memulihkan sesi…</div>;
  const alerts = data?.operational_alerts || [], scheduler = data?.scheduler_health || [], collectors = data?.collector_health || [], runs = data?.collector_runs || [], freshRows = freshness?.items || [];
  const poolRows = Object.entries(data?.database_pool || {}).map(([metric, value]) => ({ metric, value }));
  const lockRows = Object.entries(data?.pipeline_locks || {}).map(([metric, value]) => ({ metric, value: typeof value === "object" ? JSON.stringify(value) : value }));
  const status = !data ? "unknown" : data.database !== "up" || alerts.length ? "degraded" : "healthy";
  return <AppShell><header className="page-header"><div><h1 className="page-title">System Health</h1><p className="page-description">Kesehatan backend, scheduler, collector, freshness, dan kapasitas operasional.</p></div><div className="header-actions"><label className="switch-label"><input type="checkbox" checked={autoRefresh} onChange={(event) => setAutoRefresh(event.target.checked)} /> Refresh otomatis (30 dtk)</label><button className="button button-secondary button-inline" onClick={() => void load()} disabled={loading}>{loading ? "Memuat…" : "Refresh"}</button></div></header><p className="meta-row">Terakhir diperbarui: {updatedAt ? formatWib(updatedAt.toISOString()) : "-"}{freshness ? ` · Batas stale: ${freshness.stale_after_minutes} menit` : ""}</p>
    {error && <div className="alert-box error-box"><span>{error.message}</span><button className="button button-secondary button-inline" onClick={() => void load()}>Coba lagi</button>{error.requestId && <small>Request ID: {error.requestId}</small>}</div>}
    {loading && !data ? <section className="panel">Memuat status operasional…</section> : <><section className="kpi-grid five"><Kpi label="Status Sistem" value={<StatusBadge value={status} />} /><Kpi label="Database" value={<StatusBadge value={data?.database} />} /><Kpi label="Job Tertinggal" value={data?.scheduler_queue.lagging_jobs ?? 0} /><Kpi label="Operational Alert" value={alerts.length} /><Kpi label="Metric / menit" value={formatNumber(data?.raw_metric_write_rate.per_minute_last_hour)} /></section><section className="section-block"><h2 className="section-title">Kapasitas dan Pipeline</h2><div className="kpi-grid four"><Kpi label="Snapshot Metric" value={formatNumber(data?.metrics_latest_snapshot)} /><Kpi label="Missed Window" value={data?.scheduler_queue.misfire_count ?? 0} /><Kpi label="Write 1 Jam" value={formatNumber(data?.raw_metric_write_rate.last_hour)} /><Kpi label="Insiden Aktif" value={data?.incidents_active ?? 0} /></div></section><div className="notice">{data?.scheduler_queue.note || "Queue scheduler belum tersedia."}</div>
      <div className="overview-split equal"><Table title="Database Pool" headers={["Metrik", "Nilai"]} rows={poolRows} csvRows={poolRows.map((r) => [String(r.metric), String(r.value ?? "-")])} render={(r) => <tr key={String(cell(r,"metric"))}><td>{String(cell(r,"metric"))}</td><td>{String(cell(r,"value") ?? "-")}</td></tr>} /><Table title="Pipeline Locks" headers={["Scope", "Status"]} rows={lockRows} csvRows={lockRows.map((r) => [String(r.metric), String(r.value ?? "-")])} render={(r) => <tr key={String(cell(r,"metric"))}><td>{String(cell(r,"metric"))}</td><td>{String(cell(r,"value") ?? "-")}</td></tr>} /></div>
      <Table title="Operational Alerts" headers={["Job", "Severity", "Alasan", "Pesan aman"]} rows={alerts} csvRows={alerts.map((r) => [cell(r,"job_name"), cell(r,"severity"), cell(r,"reason"), cell(r,"message")])} render={(r) => <tr key={`${cell(r,"job_name")}-${cell(r,"reason")}`}><td>{String(cell(r,"job_name") || "-")}</td><td><StatusBadge value={String(cell(r,"severity") || "unknown")} /></td><td>{String(cell(r,"reason") || "-").replaceAll("_", " ")}</td><td>{String(cell(r,"message") || "-")}</td></tr>} />
      <Table title="Scheduler Health" headers={["Job", "Status", "Interval", "Heartbeat", "Umur", "Lag", "Gagal", "Durasi"]} rows={scheduler} csvRows={scheduler.map((r) => [cell(r,"job_name"), cell(r,"state"), formatAge(Number(cell(r,"expected_interval_seconds"))), formatWib(cell(r,"last_heartbeat_at") as string), formatAge(Number(cell(r,"heartbeat_age_seconds"))), formatAge(Number(cell(r,"schedule_lag_seconds"))), cell(r,"consecutive_failures"), formatNumber(Number(cell(r,"last_duration_ms")), " ms")])} render={(r) => <tr key={String(cell(r,"job_name"))}><td>{String(cell(r,"job_name") || "-")}</td><td><StatusBadge value={String(cell(r,"state") || "unknown")} /></td><td>{formatAge(Number(cell(r,"expected_interval_seconds")))}</td><td>{formatWib(cell(r,"last_heartbeat_at") as string)}</td><td>{formatAge(Number(cell(r,"heartbeat_age_seconds")))}</td><td>{formatAge(Number(cell(r,"schedule_lag_seconds")))}</td><td>{String(cell(r,"consecutive_failures") ?? "-")}</td><td>{formatNumber(Number(cell(r,"last_duration_ms")), " ms")}</td></tr>} />
      <Table title={`Collector Health (${data?.collector_health_window_hours || 24} jam)`} headers={["Collector", "Status", "Sukses", "Sampel", "Timeout", "OID", "Tindakan triage"]} rows={collectors} csvRows={collectors.map((r) => [cell(r,"collector"), cell(r,"state"), `${formatNumber(Number(cell(r,"success_rate_percent")))}%`, cell(r,"sample_count"), cell(r,"timeout_count"), cell(r,"unsupported_oid_count"), cell(r,"action")])} render={(r) => <tr key={String(cell(r,"collector"))}><td>{String(cell(r,"collector") || "-")}</td><td><StatusBadge value={String(cell(r,"state") || "unknown")} /></td><td>{formatNumber(Number(cell(r,"success_rate_percent")))}%</td><td>{String(cell(r,"sample_count") ?? 0)}</td><td>{String(cell(r,"timeout_count") ?? 0)}</td><td>{String(cell(r,"unsupported_oid_count") ?? 0)}</td><td>{String(cell(r,"action") || "-")}</td></tr>} />
      <Table title="Freshness per Collector dan Site" headers={["Collector", "Site", "Status", "Device", "Fresh", "Stale", "Tanpa data", "Check terakhir"]} rows={freshRows} csvRows={freshRows.map((r) => [cell(r,"collector"), cell(r,"site"), cell(r,"freshness_status"), cell(r,"total_devices"), cell(r,"fresh_devices"), cell(r,"stale_devices"), cell(r,"no_data_devices"), formatWib(cell(r,"latest_checked_at") as string)])} render={(r) => <tr key={`${cell(r,"collector")}-${cell(r,"site")}`}><td>{String(cell(r,"collector") || "-")}</td><td>{String(cell(r,"site") || "-")}</td><td><StatusBadge value={String(cell(r,"freshness_status") || "unknown")} /></td><td>{String(cell(r,"total_devices") ?? 0)}</td><td>{String(cell(r,"fresh_devices") ?? 0)}</td><td>{String(cell(r,"stale_devices") ?? 0)}</td><td>{String(cell(r,"no_data_devices") ?? 0)}</td><td>{formatWib(cell(r,"latest_checked_at") as string)}</td></tr>} />
      <div className="overview-split equal"><Table title="Collector Runs" headers={["Collector", "Run", "Sukses", "Rata-rata", "Maks", "Write", "Terakhir"]} rows={runs} csvRows={runs.map((r) => [cell(r,"collector"), cell(r,"runs"), cell(r,"successful_runs"), formatNumber(Number(cell(r,"average_duration_ms")), " ms"), formatNumber(Number(cell(r,"max_duration_ms")), " ms"), cell(r,"metric_writes"), formatWib(cell(r,"last_checked_at") as string)])} render={(r) => <tr key={String(cell(r,"collector"))}><td>{String(cell(r,"collector") || "-")}</td><td>{String(cell(r,"runs") ?? 0)}</td><td>{String(cell(r,"successful_runs") ?? 0)}</td><td>{formatNumber(Number(cell(r,"average_duration_ms")), " ms")}</td><td>{formatNumber(Number(cell(r,"max_duration_ms")), " ms")}</td><td>{String(cell(r,"metric_writes") ?? 0)}</td><td>{formatWib(cell(r,"last_checked_at") as string)}</td></tr>} /><Table title="Performance Budget API" headers={["Endpoint", "P95 maksimum", "Payload maksimum", "Catatan"]} rows={budgets as unknown as Row[]} csvRows={budgets.map((r) => [r.endpoint, formatNumber(r.max_p95_ms, " ms"), r.max_payload_rows, r.notes])} render={(r) => <tr key={String(cell(r,"endpoint"))}><td>{String(cell(r,"endpoint"))}</td><td>{formatNumber(Number(cell(r,"max_p95_ms")), " ms")}</td><td>{String(cell(r,"max_payload_rows"))}</td><td>{String(cell(r,"notes"))}</td></tr>} /></div></>}</AppShell>;
}
