"use client";
import { useCallback, useEffect, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { StatusBadge } from "@/components/status-badge";
import { ApiError, apiRequest } from "@/lib/api";
import { useAuth } from "@/lib/auth";
import { formatNumber, formatWib } from "@/lib/presentation";
type Threshold = { id: number; key: string; value: number; description?: string | null };
type Override = { id: number; threshold_key: string; value: number; device_id?: number | null; device_type?: string | null; site?: string | null; description?: string | null; is_active: boolean; updated_at: string };
type Window = { id: number; name: string; device_id?: number | null; site?: string | null; starts_at: string; ends_at: string; reason?: string | null; is_active: boolean; created_by?: string | null };
export function ThresholdsDashboard() {
 const { ready,user,token }=useAuth(); const [thresholds,setThresholds]=useState<Threshold[]>([]); const [overrides,setOverrides]=useState<Override[]>([]); const [windows,setWindows]=useState<Window[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<ApiError|null>(null);
 const load=useCallback(async()=>{if(!token)return;setError(null);try{const [a,b,c]=await Promise.all([apiRequest<Threshold[]>("/thresholds",{cache:"no-store"},token),apiRequest<Override[]>("/thresholds/overrides",{cache:"no-store"},token),apiRequest<Window[]>("/thresholds/maintenance-windows",{cache:"no-store"},token)]);setThresholds(a);setOverrides(b);setWindows(c)}catch(e){setError(e instanceof ApiError?e:new ApiError(0,"Koneksi ke backend gagal."))}finally{setLoading(false)}},[token]); useEffect(()=>{if(ready&&token)void load()},[ready,token,load]);
 const update=async(row:Threshold)=>{if(!token)return;const raw=window.prompt(`Nilai baru untuk ${row.key}`,String(row.value));if(raw===null)return;const value=Number(raw);if(!Number.isFinite(value)){setError(new ApiError(422,"Nilai threshold harus berupa angka."));return}try{await apiRequest(`/thresholds/${encodeURIComponent(row.key)}`,{method:"PUT",body:JSON.stringify({value})},token);await load()}catch(e){setError(e instanceof ApiError?e:new ApiError(0,"Threshold gagal diperbarui."))}};
 const deactivate=async(path:string)=>{if(!token||!window.confirm("Nonaktifkan item ini?"))return;try{await apiRequest(path,{method:"DELETE"},token);await load()}catch(e){setError(e instanceof ApiError?e:new ApiError(0,"Item gagal dinonaktifkan."))}};
 if(!ready||!user)return <div className="login">Memulihkan sesi…</div>; return <AppShell><header className="page-header"><div><h1 className="page-title">Thresholds</h1><p className="page-description">Policy runtime alert. Override device/type/site menggantikan global sesuai precedence backend; maintenance menekan alert pada rentangnya.</p></div><button className="button button-secondary button-inline" onClick={()=>void load()}>Refresh</button></header>{error&&<div className="alert-box error-box"><span>{error.message}</span><button className="button button-secondary button-inline" onClick={()=>void load()}>Coba lagi</button></div>}{loading?<section className="panel">Memuat policy runtime…</section>:<><Table title="Global Threshold" headers={["Key","Nilai","Deskripsi","Aksi"]}><tbody>{thresholds.map(r=><tr key={r.id}><td>{r.key}</td><td>{formatNumber(r.value)}</td><td>{r.description||"-"}</td><td>{user.role==="admin"&&<button className="text-button" onClick={()=>void update(r)}>Edit</button>}</td></tr>)}</tbody></Table><Table title="Threshold Override" headers={["Key","Nilai","Scope","Deskripsi","Status","Diubah","Aksi"]}><tbody>{overrides.map(r=><tr key={r.id}><td>{r.threshold_key}</td><td>{formatNumber(r.value)}</td><td>{r.device_id?`Device #${r.device_id}`:r.site?`Site: ${r.site}`:r.device_type?`Type: ${r.device_type}`:"-"}</td><td>{r.description||"-"}</td><td><StatusBadge value={r.is_active?"active":"inactive"}/></td><td>{formatWib(r.updated_at)}</td><td>{user.role==="admin"&&r.is_active&&<button className="text-button danger" onClick={()=>void deactivate(`/thresholds/overrides/${r.id}`)}>Nonaktifkan</button>}</td></tr>)}</tbody></Table><Table title="Maintenance Windows" headers={["Nama","Scope","Mulai","Selesai","Alasan","Status","Aksi"]}><tbody>{windows.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.device_id?`Device #${r.device_id}`:r.site?`Site: ${r.site}`:"Global"}</td><td>{formatWib(r.starts_at)}</td><td>{formatWib(r.ends_at)}</td><td>{r.reason||"-"}</td><td><StatusBadge value={r.is_active?"active":"inactive"}/></td><td>{user.role==="admin"&&r.is_active&&<button className="text-button danger" onClick={()=>void deactivate(`/thresholds/maintenance-windows/${r.id}`)}>Nonaktifkan</button>}</td></tr>)}</tbody></Table></>}</AppShell>}
function Table({title,headers,children}:{title:string;headers:string[];children:React.ReactNode}){return <section className="panel table-panel"><div className="section-heading"><h2>{title}</h2></div><div className="table-scroll"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead>{children}</table></div></section>}
