"use client";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { apiFetch } from "@/lib/api/client";
import { formatWib } from "@/lib/formatters";
import { PageHeader } from "@/components/ui/page-header";
import { DataTable } from "@/components/ui/data-table";
import { LoadingState, ErrorState } from "@/components/ui/page-state";
type Threshold={id:number;key:string;value:number;description:string|null};type Override={id:number;threshold_key:string;value:number;device_id:number|null;device_type:string|null;site:string|null;description:string|null;is_active:boolean;created_at:string};type Window={id:number;name:string;site:string|null;starts_at:string;ends_at:string;reason:string|null;is_active:boolean};
export function ThresholdsPage(){const[t,setT]=useState<"global"|"overrides"|"maintenance">("global");const a=useQuery({queryKey:["thresholds"],queryFn:()=>apiFetch<Threshold[]>("/thresholds")});const b=useQuery({queryKey:["threshold-overrides"],queryFn:()=>apiFetch<Override[]>("/thresholds/overrides")});const c=useQuery({queryKey:["maintenance"],queryFn:()=>apiFetch<Window[]>("/thresholds/maintenance-windows")});if(a.isPending||b.isPending||c.isPending)return <LoadingState/>;if(a.isError||b.isError||c.isError)return <ErrorState message="Policy threshold tidak dapat dimuat." onRetry={()=>{void a.refetch();void b.refetch();void c.refetch()}}/>;return <main className="app-page"><PageHeader title="Thresholds" description="Policy global, override terarah, dan maintenance window."/><div className="tab-list"><button className={t==="global"?"tab-active":""} onClick={()=>setT("global")}>Global</button><button className={t==="overrides"?"tab-active":""} onClick={()=>setT("overrides")}>Overrides</button><button className={t==="maintenance"?"tab-active":""} onClick={()=>setT("maintenance")}>Maintenance</button></div>{t==="global"?<DataTable columns={[{key:"key",label:"Key",render:x=>x.key},{key:"value",label:"Nilai",render:x=>x.value},{key:"description",label:"Deskripsi",render:x=>x.description??"-"}]} rows={a.data}/>:t==="overrides"?<DataTable columns={[{key:"key",label:"Threshold",render:x=>x.threshold_key},{key:"value",label:"Nilai",render:x=>x.value},{key:"scope",label:"Scope",render:x=>x.site??x.device_type??x.device_id??"Global"},{key:"status",label:"Status",render:x=>x.is_active?"Aktif":"Nonaktif"},{key:"at",label:"Dibuat",render:x=>formatWib(x.created_at)}]} rows={b.data}/>:<DataTable columns={[{key:"name",label:"Nama",render:x=>x.name},{key:"site",label:"Site",render:x=>x.site??"-"},{key:"start",label:"Mulai",render:x=>formatWib(x.starts_at)},{key:"end",label:"Selesai",render:x=>formatWib(x.ends_at)},{key:"status",label:"Status",render:x=>x.is_active?"Aktif":"Nonaktif"}]} rows={c.data}/>}</main>}
