"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { DataTable } from "@/components/ui/data-table";
import { PageHeader } from "@/components/ui/page-header";
import { ErrorState, LoadingState } from "@/components/ui/page-state";
import { PermissionGate } from "@/components/ui/permission-gate";
import { apiFetch } from "@/lib/api/client";
import { formatWib } from "@/lib/formatters";

type Threshold = { id: number; key: string; value: number; description: string | null };
type Override = { id: number; threshold_key: string; value: number; device_id: number | null; device_type: string | null; site: string | null; description: string | null; is_active: boolean; created_at: string };
type Window = { id: number; name: string; site: string | null; starts_at: string; ends_at: string; reason: string | null; is_active: boolean };

export function ThresholdsPage() {
  const [tab, setTab] = useState<"global" | "overrides" | "maintenance">("global");
  const [editing, setEditing] = useState<Threshold | null>(null);
  const [override, setOverride] = useState({ threshold_key: "", value: "", site: "", device_type: "", description: "" });
  const [windowForm, setWindowForm] = useState({ name: "", site: "", starts_at: "", ends_at: "", reason: "" });
  const client = useQueryClient();
  const thresholds = useQuery({ queryKey: ["thresholds"], queryFn: () => apiFetch<Threshold[]>("/thresholds") });
  const overrides = useQuery({ queryKey: ["threshold-overrides"], queryFn: () => apiFetch<Override[]>("/thresholds/overrides") });
  const windows = useQuery({ queryKey: ["maintenance"], queryFn: () => apiFetch<Window[]>("/thresholds/maintenance-windows") });
  const refresh = () => Promise.all([client.invalidateQueries({ queryKey: ["thresholds"] }), client.invalidateQueries({ queryKey: ["threshold-overrides"] }), client.invalidateQueries({ queryKey: ["maintenance"] })]);
  const update = useMutation({ mutationFn: (item: Threshold) => apiFetch(`/thresholds/${item.key}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ value: item.value }) }), onSuccess: refresh });
  const createOverride = useMutation({ mutationFn: () => apiFetch("/thresholds/overrides", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ threshold_key: override.threshold_key, value: Number(override.value), site: override.site || null, device_type: override.device_type || null, description: override.description || null }) }), onSuccess: () => { setOverride({ threshold_key: "", value: "", site: "", device_type: "", description: "" }); return refresh(); } });
  const createWindow = useMutation({ mutationFn: () => apiFetch("/thresholds/maintenance-windows", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...windowForm, site: windowForm.site || null, reason: windowForm.reason || null, starts_at: new Date(windowForm.starts_at).toISOString(), ends_at: new Date(windowForm.ends_at).toISOString() }) }), onSuccess: () => { setWindowForm({ name: "", site: "", starts_at: "", ends_at: "", reason: "" }); return refresh(); } });
  const deactivate = useMutation({ mutationFn: ({ path }: { path: string }) => apiFetch(path, { method: "DELETE" }), onSuccess: refresh });
  if (thresholds.isPending || overrides.isPending || windows.isPending) return <LoadingState />;
  if (thresholds.isError || overrides.isError || windows.isError) return <ErrorState message="Policy threshold tidak dapat dimuat." onRetry={() => { void thresholds.refetch(); void overrides.refetch(); void windows.refetch(); }} />;
  const input = (value: string, onChange: (value: string) => void, type = "text") => <input type={type} value={value} onChange={(event) => onChange(event.target.value)} required />;
  return <main className="app-page"><PageHeader title="Thresholds" description="Policy global, override terarah, dan maintenance window." /><div className="tab-list">{(["global", "overrides", "maintenance"] as const).map((item) => <button key={item} className={tab === item ? "tab-active" : ""} onClick={() => setTab(item)}>{item === "global" ? "Global" : item === "overrides" ? "Overrides" : "Maintenance"}</button>)}</div>
    {tab === "global" ? <><DataTable columns={[{ key: "key", label: "Key", render: (item) => item.key }, { key: "value", label: "Nilai", render: (item) => item.value }, { key: "description", label: "Deskripsi", render: (item) => item.description ?? "-" }, { key: "action", label: "Aksi", render: (item) => <PermissionGate><button className="button-secondary" onClick={() => setEditing({ ...item })}>Edit</button></PermissionGate> }]} rows={thresholds.data} />{editing ? <PermissionGate><form className="device-form" onSubmit={(event) => { event.preventDefault(); update.mutate(editing); setEditing(null); }}><label>Threshold<input type="number" step="any" value={editing.value} onChange={(event) => setEditing({ ...editing, value: Number(event.target.value) })} /></label><div className="inline-actions"><button type="submit">Simpan</button><button type="button" className="button-secondary" onClick={() => setEditing(null)}>Batal</button></div></form></PermissionGate> : null}</> : null}
    {tab === "overrides" ? <><PermissionGate><form className="device-form" onSubmit={(event) => { event.preventDefault(); createOverride.mutate(); }}><label>Threshold key{input(override.threshold_key, (value) => setOverride({ ...override, threshold_key: value }))}</label><label>Nilai{input(override.value, (value) => setOverride({ ...override, value }), "number")}</label><label>Site{input(override.site, (value) => setOverride({ ...override, site: value }))}</label><label>Device type{input(override.device_type, (value) => setOverride({ ...override, device_type: value }))}</label><label className="form-span-2">Deskripsi{input(override.description, (value) => setOverride({ ...override, description: value }))}</label><button type="submit" disabled={createOverride.isPending}>Tambah override</button></form></PermissionGate><DataTable columns={[{ key: "key", label: "Threshold", render: (item) => item.threshold_key }, { key: "value", label: "Nilai", render: (item) => item.value }, { key: "scope", label: "Scope", render: (item) => item.site ?? item.device_type ?? item.device_id ?? "Global" }, { key: "status", label: "Status", render: (item) => item.is_active ? "Aktif" : "Nonaktif" }, { key: "action", label: "Aksi", render: (item) => item.is_active ? <PermissionGate><button className="button-danger" onClick={() => deactivate.mutate({ path: `/thresholds/overrides/${item.id}` })}>Nonaktifkan</button></PermissionGate> : "-" }]} rows={overrides.data} /></> : null}
    {tab === "maintenance" ? <><PermissionGate><form className="device-form" onSubmit={(event) => { event.preventDefault(); createWindow.mutate(); }}><label>Nama{input(windowForm.name, (value) => setWindowForm({ ...windowForm, name: value }))}</label><label>Site{input(windowForm.site, (value) => setWindowForm({ ...windowForm, site: value }))}</label><label>Mulai{input(windowForm.starts_at, (value) => setWindowForm({ ...windowForm, starts_at: value }), "datetime-local")}</label><label>Selesai{input(windowForm.ends_at, (value) => setWindowForm({ ...windowForm, ends_at: value }), "datetime-local")}</label><label className="form-span-2">Alasan{input(windowForm.reason, (value) => setWindowForm({ ...windowForm, reason: value }))}</label><button type="submit" disabled={createWindow.isPending}>Tambah maintenance</button></form></PermissionGate><DataTable columns={[{ key: "name", label: "Nama", render: (item) => item.name }, { key: "site", label: "Site", render: (item) => item.site ?? "-" }, { key: "start", label: "Mulai", render: (item) => formatWib(item.starts_at) }, { key: "end", label: "Selesai", render: (item) => formatWib(item.ends_at) }, { key: "status", label: "Status", render: (item) => item.is_active ? "Aktif" : "Nonaktif" }, { key: "action", label: "Aksi", render: (item) => item.is_active ? <PermissionGate><button className="button-danger" onClick={() => deactivate.mutate({ path: `/thresholds/maintenance-windows/${item.id}` })}>Nonaktifkan</button></PermissionGate> : "-" }]} rows={windows.data} /></> : null}
  </main>;
}
