"use client";
import { useEffect, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { apiFetch } from "@/lib/api/client";
import { formatWib } from "@/lib/formatters";
import { LoadingState, ErrorState } from "@/components/ui/page-state";
import { PermissionGate } from "@/components/ui/permission-gate";
import { StatusBadge } from "@/components/ui/status-badge";
import type { Incident, IncidentTimelineEvent, IncidentWorkflow } from "./types";

export function IncidentDetail({ incident, onClose, onSaveWorkflow }: { incident: Incident; onClose: () => void; onSaveWorkflow: (workflow: IncidentWorkflow) => void }) {
  const [workflow, setWorkflow] = useState<IncidentWorkflow>({ owner: incident.owner, assignee: incident.assignee, severity_override: incident.severity_override, note: incident.note });
  useEffect(() => setWorkflow({ owner: incident.owner, assignee: incident.assignee, severity_override: incident.severity_override, note: incident.note }), [incident]);
  const timeline = useQuery({ queryKey: ["incident", incident.id, "timeline"], queryFn: () => apiFetch<{ items: IncidentTimelineEvent[] }>(`/incidents/${incident.id}/timeline`) });
  return <div className="dialog-backdrop"><section className="dialog incident-dialog" role="dialog" aria-modal="true" aria-labelledby="incident-dialog-title"><header className="section-header"><div><h2 id="incident-dialog-title">Insiden #{incident.id}</h2><p>{incident.summary}</p></div><button className="button-secondary" onClick={onClose}>Tutup</button></header><dl className="meta-strip"><div><dt>Device</dt><dd>{incident.device_name ?? "-"}</dd></div><div><dt>Site</dt><dd>{incident.site ?? "-"}</dd></div><div><dt>Mulai</dt><dd>{formatWib(incident.started_at)}</dd></div><div><dt>Severity</dt><dd><StatusBadge value={incident.effective_severity} /></dd></div><div><dt>Status</dt><dd><StatusBadge value={incident.status} /></dd></div><div><dt>Diakui</dt><dd>{formatWib(incident.acknowledged_at)}</dd></div></dl><PermissionGate><section><h3>Workflow</h3><form className="device-form" onSubmit={(event) => { event.preventDefault(); onSaveWorkflow(workflow); }}><label>Owner<input value={workflow.owner ?? ""} onChange={(event) => setWorkflow({ ...workflow, owner: event.target.value || null })} /></label><label>Assignee<input value={workflow.assignee ?? ""} onChange={(event) => setWorkflow({ ...workflow, assignee: event.target.value || null })} /></label><label>Severity override<select value={workflow.severity_override ?? ""} onChange={(event) => setWorkflow({ ...workflow, severity_override: event.target.value || null })}><option value="">Gunakan severity otomatis</option>{["critical", "high", "warning", "info"].map((value) => <option key={value} value={value}>{value}</option>)}</select></label><label className="form-span-2">Catatan<textarea rows={3} value={workflow.note ?? ""} onChange={(event) => setWorkflow({ ...workflow, note: event.target.value || null })} /></label><button type="submit">Simpan workflow</button></form></section></PermissionGate><section><h3>Timeline</h3>{timeline.isPending ? <LoadingState /> : timeline.isError ? <ErrorState message="Timeline tidak dapat dimuat." onRetry={() => void timeline.refetch()} /> : <ol className="timeline">{timeline.data.items.map((item) => <li key={item.id}><strong>{item.event_type}</strong> — {item.message} <small>{formatWib(item.created_at)} · {item.actor ?? "system"}</small></li>)}</ol>}</section></section></div>;
}
