"use client";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { apiFetch, withQuery } from "@/lib/api/client";
import { formatWib } from "@/lib/formatters";
import { PageHeader } from "@/components/ui/page-header";
import { MetaStrip } from "@/components/ui/meta-strip";
import { MetricCard, MetricGrid } from "@/components/ui/metric-card";
import { DataTable } from "@/components/ui/data-table";
import { Pagination } from "@/components/ui/pagination";
import { CsvExport } from "@/components/ui/csv-export";
import { StatusBadge } from "@/components/ui/status-badge";
import { ErrorState, LoadingState } from "@/components/ui/page-state";
type Incident={id:number;device_name:string|null;site:string|null;status:string;summary:string;owner:string|null;assignee:string|null;effective_severity:string|null;acknowledged_at:string|null;started_at:string;ended_at:string|null};type Page={items:Incident[];meta:{total:number;limit:number;offset:number}};const LIMIT=50;
export function IncidentsPage(){const[status,setStatus]=useState("");const[search,setSearch]=useState("");const[offset,setOffset]=useState(0);const incidents=useQuery({queryKey:["incidents",status,search,offset],queryFn:()=>apiFetch<Page>(withQuery("/incidents/paged",{status,search,limit:LIMIT,offset})),refetchInterval:15_000});if(incidents.isPending)return <LoadingState/>;if(incidents.isError)return <ErrorState message="Insiden tidak dapat dimuat." onRetry={()=>void incidents.refetch()}/>;const data=incidents.data;const active=data.items.filter(x=>x.status!=="resolved").length;const acknowledged=data.items.filter(x=>x.acknowledged_at).length;return <main className="app-page"><PageHeader title="Incidents" description="Insiden aktif, owner, dan status penanganan operasional."/><MetaStrip items={[{label:"Refresh otomatis",value:"Aktif (15 dtk)"},{label:"Total",value:data.meta.total},{label:"Terakhir dirender",value:formatWib(new Date().toISOString())}]}/><MetricGrid>{[["Total",data.meta.total],["Aktif",active],["Sudah di-ack",acknowledged],["Belum di-ack",active-acknowledged]].map(([l,v])=><MetricCard key={String(l)} label={String(l)} value={String(v)}/>)}</MetricGrid><div className="filter-panel"><label>Status<select value={status} onChange={e=>{setStatus(e.target.value);setOffset(0)}}><option value="">Semua</option>{["open","acknowledged","resolved"].map(x=><option key={x}>{x}</option>)}</select></label><label>Cari<input value={search} placeholder="Device atau ringkasan" onChange={e=>{setSearch(e.target.value);setOffset(0)}}/></label></div><div className="section-header"><h2>Daftar Insiden</h2><CsvExport filename="incidents.csv" columns={["Mulai WIB","Device","Site","Severity","Status","Owner","Assignee","Ringkasan"]} rows={data.items.map(x=>[formatWib(x.started_at),x.device_name,x.site,x.effective_severity,x.status,x.owner,x.assignee,x.summary])}/></div><DataTable columns={[{key:"started",label:"Mulai (WIB)",render:x=>formatWib(x.started_at)},{key:"device",label:"Device",render:x=>x.device_name??"-"},{key:"site",label:"Site",render:x=>x.site??"-"},{key:"severity",label:"Severity",render:x=><StatusBadge value={x.effective_severity}/>},{key:"status",label:"Status",render:x=><StatusBadge value={x.status}/>},{key:"owner",label:"Owner / Assignee",render:x=>[x.owner,x.assignee].filter(Boolean).join(" / ")||"-"},{key:"summary",label:"Ringkasan",render:x=>x.summary}]} rows={data.items}/><Pagination offset={offset} limit={LIMIT} total={data.meta.total} onChange={setOffset}/></main>}
